### ISSUE TITLE
Set an examples page for development

### ISSUE THREAD

**Issue by cdc-mgz4** [reichlab/d3-foresight#10]
This should look like what you had. Doesn't have to be 100% functional or perfect, just enough to test what we need.

**Comment by lepisma** [comment]
Since its just us, I would recommend using `test-foresight` branch from https://github.com/reichlab/flusight/tree/test-foresight. I have disabled map and other stuff and am keeping it up to date with the current version of foresight. Plus, you get data for free there.
Also, the version of `d3-foresight` is pinned to 0.1.0, so you might need to link the development version from here as the preferred package in there.

**Comment by cdc-mgz4** [comment]
I think this package should have it's own stand alone development. It's not a very good idea to depend on the original source for development.

**Comment by lepisma** [comment]
Development is going to be self contained and standalone. I am removing components *from* flusight and adding here, not the other way around.

The point is, data expected by the functions are in a certain format and its much easier to use flusight as the test bed for handling those transformations and providing parsed data as of now. It is also important since the transformation from `data.json` to arguments of `TimeChart` is not crucial for `d3-foresight` because there is no `data.json` in the usage scenario of `d3-foresight` (e.g. other users might have different data source for creating these arguments). The only important thing, the data argument for `TimeChart`, is already provided by flusight and it will be wasteful to repeat the transformations from `data.json` to those arguments in this repo.

Once foresight gets decoupled (a bunch of issues gets closed), it will be easy to just document the argument structure and go on with that to create standalone examples.
