### ISSUE TITLE
Recent historical data not showing up until year is manually loaded

### ISSUE THREAD

**Issue by nickreich** [reichlab/d3-foresight#63]
I noticed a strange bug in the FluSightNetwork.io visualization. I will illustrate in 3 pictures.

When I first load the page and click through to the mountain west region I see this (after disabling the models, so we can see it better):
![image](https://user-images.githubusercontent.com/1280767/68649755-bfea0280-0523-11ea-8512-d0b52a8eb430.png)

I noticed when looking at this image that the historical grey line from 2018/2019 was not visible. This line is distinct because in October the hospitals reporting data to the CDC ILINet system changed and the baseline rose quite a bit. So then I clicked over to the 2018/2019 visualization:

![image](https://user-images.githubusercontent.com/1280767/68649832-ee67dd80-0523-11ea-9466-d4256430e8cb.png)

Here you can see really clearly the rise in baseline as of the 2018/2019 season.

Now, if I go back to the 2019/2020 season, the line from the 2018/2019 now *is* visible!
![image](https://user-images.githubusercontent.com/1280767/68649922-1a835e80-0524-11ea-8f2f-7283b6e6fef0.png)

In essence the first and third picture should in theory be exactly the same, but for some reason the 2018/2019 historical line doesn't load by default in the initial load.

**Comment by lepisma** [comment]
I have an inkling of why this _might_ be happening. The general mechanism of collecting history is:
1. download fixed data for 2003 to 2014 seasons ([here](https://github.com/reichlab/flusight/blob/master/scripts/get-history.js#L10))
2. use the active season information to support history for the rest (this happens on builds IIRC)

For rendering history, we look at our store of loaded seasons and show whatever we have _before_ the current season. Somehow the 2018/2019 season is missing here. When we explicitly demand the season, the item goes in our history storage and subsequent history renders are fine. This looks like a missed update for a parameter somewhere which should have been documented in a checklist for new seasons.

@katiehouse3 , @Khoale1096 let me know if you have found a fix. Else I will try a patch this weekend, if not before.

**Comment by Khoale1096** [comment]
Hi all. It was a while since any updates have been made on this issue. I noticed that the problem also happened to other previous seasons starting from 2015/2016 -> 2018/2019. After some debugging, I'm seeing that the visualization only fetch information from the current season (i.e 2019/2020 this year) when the site was first loaded, rather than loading all previous seasons before 2019/2020.

I felt that this is contradicting to what Abhinav said in the previous comment "For rendering history, we look at our store of loaded seasons and show whatever we have before the current season", so I want to make sure that I'm debugging correctly. Can @lepisma or @katiehouse3 point me to the code/file that perform the "For rendering history, we look at our store of loaded seasons and show whatever we have before the current season"? That would be a great help! Thanks!

**Comment by Khoale1096** [comment]
Updates: I have attempted a fix on this issue. This is the current version on my localhost with all the seasons before the current season being shown when the site is first loaded.
<img width="886" alt="Screenshot (196)" src="https://user-images.githubusercontent.com/31902663/72398119-e5f07680-370f-11ea-9ae5-036384b2cfdc.png">
I will create a pull request for this fix on the cdc-flusight-ensemble repository, and close this issue, after discussing with Nick about certain aspects related to my fix.

**Comment by lepisma** [comment]
extremely sorry for the delay.

before anything else, [the fix](https://github.com/FluSightNetwork/cdc-flusight-ensemble/pull/275) changes the history file during build so that should work nicely without worrying about how we do the rendering. the code issue still is going to be there for other flusight deployments but those again can be mitigated by keeping the history list be completely static (instead of partially static till 2014 and then dynamic).

[here](https://github.com/reichlab/flusight/blob/a48ce2d76579f8b4d66bbc1af2b9663fe5ecfad3/src/store/getters.js#L160-L198) is the piece which does the dynamic part of history object creation which goes for rendering.
